//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OceanFishin.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OceanFishin.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All possible area information at once..
        /// </summary>
        public static string All_possible_area_information_at_once_ {
            get {
                return ResourceManager.GetString("All possible area information at once.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balloons.
        /// </summary>
        public static string Balloons {
            get {
                return ResourceManager.GetString("Balloons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best spectral chance.
        /// </summary>
        public static string Best_spectral_chance {
            get {
                return ResourceManager.GetString("Best spectral chance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boarding is open for.
        /// </summary>
        public static string Boarding_is_open_for {
            get {
                return ResourceManager.GetString("Boarding is open for", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comprehensive.
        /// </summary>
        public static string Comprehensive {
            get {
                return ResourceManager.GetString("Comprehensive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consider Donating.
        /// </summary>
        public static string Consider_Donating {
            get {
                return ResourceManager.GetString("Consider Donating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crabs.
        /// </summary>
        public static string Crabs {
            get {
                return ResourceManager.GetString("Crabs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determines the single, best choice for you..
        /// </summary>
        public static string Determines_the_single__best_choice_for_you_ {
            get {
                return ResourceManager.GetString("Determines the single, best choice for you.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Did this plugin help you?.
        /// </summary>
        public static string Did_this_plugin_help_you_ {
            get {
                return ResourceManager.GetString("Did this plugin help you?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Mode.
        /// </summary>
        public static string Display_Mode {
            get {
                return ResourceManager.GetString("Display Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fisher&apos;s Intuition Buff.
        /// </summary>
        public static string Fisher_s_Intuition_Buff {
            get {
                return ResourceManager.GetString("Fisher\'s Intuition Buff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fugu.
        /// </summary>
        public static string Fugu {
            get {
                return ResourceManager.GetString("Fugu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hour.
        /// </summary>
        public static string hour {
            get {
                return ResourceManager.GetString("hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include suggestions for mission and achievement fish..
        /// </summary>
        public static string Include_suggestions_for_mission_and_achievement_fish_ {
            get {
                return ResourceManager.GetString("Include suggestions for mission and achievement fish.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jellyfish.
        /// </summary>
        public static string Jellyfish {
            get {
                return ResourceManager.GetString("Jellyfish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to less than a minute!.
        /// </summary>
        public static string less_than_a_minute_ {
            get {
                return ResourceManager.GetString("less than a minute!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mantas.
        /// </summary>
        public static string Mantas {
            get {
                return ResourceManager.GetString("Mantas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimal.
        /// </summary>
        public static string Minimal {
            get {
                return ResourceManager.GetString("Minimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutes.
        /// </summary>
        public static string minutes {
            get {
                return ResourceManager.GetString("minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mission Fish.
        /// </summary>
        public static string Mission_Fish {
            get {
                return ResourceManager.GetString("Mission Fish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Octopodes.
        /// </summary>
        public static string Octopodes {
            get {
                return ResourceManager.GetString("Octopodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seahorses.
        /// </summary>
        public static string Seahorses {
            get {
                return ResourceManager.GetString("Seahorses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sharks.
        /// </summary>
        public static string Sharks {
            get {
                return ResourceManager.GetString("Sharks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spectral High Points.
        /// </summary>
        public static string Spectral_High_Points {
            get {
                return ResourceManager.GetString("Spectral High Points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spectral Intuition.
        /// </summary>
        public static string Spectral_Intuition {
            get {
                return ResourceManager.GetString("Spectral Intuition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spectral Mission Fish.
        /// </summary>
        public static string Spectral_Mission_Fish {
            get {
                return ResourceManager.GetString("Spectral Mission Fish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggestions based on current conditions..
        /// </summary>
        public static string Suggestions_based_on_current_conditions_ {
            get {
                return ResourceManager.GetString("Suggestions based on current conditions.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggestions will appear here during Ocean Fishing.
        /// </summary>
        public static string Suggestions_will_appear_here_during_Ocean_Fishing {
            get {
                return ResourceManager.GetString("Suggestions will appear here during Ocean Fishing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The next boat leaves in.
        /// </summary>
        public static string The_next_boat_leaves_in {
            get {
                return ResourceManager.GetString("The next boat leaves in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for location....
        /// </summary>
        public static string Waiting_for_location___ {
            get {
                return ResourceManager.GetString("Waiting for location...", resourceCulture);
            }
        }
    }
}
